# Generated by Django 4.2.6 on 2023-11-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_alter_quiz_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='creator',
        ),
    ]
